# Generated by Django 4.1.4 on 2023-01-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alomee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Duedate',
            field=models.DateField(null=True),
        ),
    ]
